### ISSUE TITLE
Dependency on mlxComputeR

### ISSUE THREAD

**Issue by romainfrancois** [MarcLavielle/mlxR#4]
This is the last problem I have locally when I run `R CMD check`. We do a `.Call` for a function that is in the `mlxComputeR` package that we can't declare as one of our dependency as it's not on CRAN. 

```
* checking foreign function calls ... WARNING
Foreign function call to a different package:
  .Call("mlxComputeR", ..., PACKAGE = "mlxComputeR")
Undeclared package in foreign function calls:
   ‘mlxComputeR’
```

I'm not sure yet how to deal with that.

**Comment by dpastoor** [comment]
I will also throw out there that documentation for a local build would be a good idea. I was at Merck this summer and the way they have their network setup I could not for the life of me get devtools::install_github() to work, and working with some other smaller pharma companies have had the same issues due to how the firewalls are set up.
